apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP   # internal service (Ingress will expose it)
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
